# -*- coding: utf-8 -*-
"""Equity_Dashboard

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HXpuorcSQyxYjs7VUsRQUErfbrTmOKjH
"""

import yfinance as yf
import pandas as pd
import streamlit as st
from pandas.tseries.offsets import DateOffset

tickers = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')[0].Symbol

tickers = tickers.to_list()

#tickers

@st.cache_data
def getdata():
  df = yf.download(tickers,start='2021-01-01')
  df = df['Close']
  return df

df = getdata()

st.title('Index Component performance of the S&P500')

n = st.number_input('Please provide the performance horizon in months:', min_value =1, max_value=24)

#df

df[:df.index[-1] - DateOffset(months=3)].tail(1).squeeze()

def get_ret(df,n): 
  previous_prices = df[:df.index[-1] - DateOffset(months=n)].tail(1).squeeze()
  recent_prices = df.loc[df.index[-1]]
  ret_df = recent_prices/previous_prices - 1
  return previous_prices.name, ret_df

date, ret_df = get_ret(df,n)

winners, losers = ret_df.nlargest(10), ret_df.nsmallest(10)

winners.name,losers.name = 'winners','losers'

st.table(winners)
st.table(losers)

winnerpick = st.selectbox('Pick a winner to visualize:', winners.index)
st.line_chart(df[winnerpick][date:])

loserpick = st.selectbox('Pick a loser to visualize', losers.index)
st.line_chart(df[loserpick][date:])

